src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Categorie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Pays", inversedBy="pays")
     */
    private $pays;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="user")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categorie $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function getPays(): ?Pays
    {
        return $this->pays;
    }

    public function setPays(?Pays $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }
}

templates/articleSearch.html.twig
{% extends 'base.html.twig' %}
{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('assets/css/articleList.css') }}">
{% endblock %}

{% block content %}
    <div class="indexContainer">

            {% for article in article %}

                <div class="articleContainer">
                    <a href="{{ path('articleShow', {'id' : article.id}) }}">
                    <div class="imgContainer">
                        <img class="imgArticle" src="{{ asset('assets/img') }}/{{ article.picture }}" alt="image">
                    </div>
                    <h1 class="titleArticle">{{ article.titre }}</h1>
                    <div class="subtitleContainer">
                        <h2 class="subtitleArticle">Catégorie: {{ article.Categorie.libelle }}</h2>
                        <h2 class="subtitleArticle">Écrit par: {{ article.user.username }}</h2>
                        <h2 class="subtitleArticle">Pays: {{ article.pays.nomPays }}</h2>
                    </div>
                    <p>{{ article.contenu|striptags|slice(0, 755)|raw }} {{ "..." }} <a href="{{ path('articleShow',
                            {'id' : article.id}) }}" class="linkArticle">Lire plus</a> </p>
                    </a>
                </div>


            {% endfor %}

    </div>
    <a href="{{ path('index') }}">Retour</a>

{% endblock %}

templates/articleSearchShow.html.twig
{% extends 'base.html.twig' %}
{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('assets/css/articleshow.css') }}">
{% endblock %}

{% block content %}

    <div class="container">
        <div class="articleContainer">
            <div class="imgContainer">
                <img class="imgArticle" src="{{ asset('assets/img') }}/{{ article.picture }}" alt="image">
            </div>
            <h1 class="titleArticle">{{ article.titre }}</h1>
            <div class="subtitleContainer">
                <h2 class="subtitleArticle">Catégorie: {{ article.categorie.libelle }}</h2>
                <h2 class="subtitleArticle">Écrit par: {{ article.user.username }}</h2>
                <h2 class="subtitleArticle">Pays: {{ article.pays.nomPays }}</h2>
            </div>
            <p>{{ article.contenu|raw }}</p>
            <a href="{{ path('index') }}">Retour</a>
        </div>
    </div>

{% endblock %}

templates/articleShow.html.twig
{% extends 'base.html.twig' %}
{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('assets/css/articleshow.css') }}">
{% endblock %}

{% block content %}

    <div class="container">
        <div class="articleContainer">
            <div class="imgContainer">
                <img class="imgArticle" src="{{ asset('assets/img') }}/{{ article.picture }}" alt="image">
            </div>
            <h1 class="titleArticle">{{ article.titre }}</h1>
            <div class="subtitleContainer">
                <h2 class="subtitleArticle">Catégorie: {{ article.categorie.libelle }}</h2>
                <h2 class="subtitleArticle">Écrit par: {{ article.user.username }}</h2>
                <h2 class="subtitleArticle">Pays: {{ article.pays.nomPays }}</h2>
            </div>
            <p>{{ article.contenu|raw }}</p>
            <a href="{{ path('index') }}">Retour</a>
        </div>
    </div>

{% endblock %}

templates/base.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf8">
    <title>Tour du monde</title>
    <link rel="stylesheet" href="{{ asset('assets/css/styleBase.css') }}">
    {% block stylesheet %}{% endblock %}
    <script src="https://kit.fontawesome.com/21629f9ec4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
</head>
<body>
<header>
    <!-- haut du header -->
    <div class="topHeader">
        <img src="{{ asset('assets/img/logoTDM.png')}}" alt="logo" class="logoTop">
        <h1>Tour du monde</h1>
        <div class="rightHeader">
            <a href="pages/article_form.php">Connexion</a>
            <h3 class="recherche">Recherche</h3>
            <input type="text" class="barreRecherche">
        </div>
    </div>
    <!-- haut du header -->

    <!-- navbar -->
    <nav>
        <ul class="navbar">
            <li><a href="#">Présentation</a></li>
            <li>
                <a href="#" id="drop">Destinations</a>
                <i class="fas fa-sort-down" id="dropdown1"></i>
                <ul class="dropdownDestinations" id="dropdownDestinations">
                    <li><a href="#">Afrique</a>
                        <i class="fas fa-caret-right" id="dropdown2"></i>
                        <ul class="dropdownAfrique dropdown" id="dropdownAfrique">
                            <li><a href="#">Afrique du sud</a></li>
                            <li><a href="#">Gabon</a></li>
                            <li><a href="#">Mali</a></li>
                            <li><a href="#">Maroc</a></li>
                            <li><a href="#">Bénin</a></li>
                            <li><a href="#">Sénégal</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Amérique du nord</a>
                        <i class="fas fa-caret-right" id="dropdown3"></i>
                        <ul class="dropdownAmeriqueNord dropdown" id="dropdownAmeriqueNord">
                            <li><a href="#">Canada</a></li>
                            <li><a href="#">Mexique</a></li>
                            <li><a href="#">U.S.A</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Amérique du sud</a>
                        <i class="fas fa-caret-right" id="dropdown4"></i>
                        <ul class="dropdownAmeriqueSud dropdown" id="dropdownAmeriqueSud">
                            <li><a href="#">Argentine</a></li>
                            <li><a href="#">Bolivie</a></li>
                            <li><a href="#">Brésil</a></li>
                            <li><a href="#">Chili</a></li>
                            <li><a href="#">Colombie</a></li>
                            <li><a href="#">Pérou</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Asie</a>
                        <i class="fas fa-caret-right" id="dropdown5"></i>
                        <ul class="dropdownAsie dropdown" id="dropdownAsie">
                            <li><a href="#">Birmanie</a></li>
                            <li><a href="#">Cambodge</a></li>
                            <li><a href="#">Népal</a></li>
                            <li><a href="#">Philippines</a></li>
                            <li><a href="#">Thaïlande</a></li>
                            <li><a href="#">Vietnam</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Europe</a>
                        <i class="fas fa-caret-right" id="dropdown6"></i>
                        <ul class="dropdownEurope" id="dropdownEurope">
                            <li><a href="#">Croatie</a></li>
                            <li><a href="#">Espagne</a></li>
                            <li><a href="#">France</a></li>
                            <li><a href="#">Hongrie</a></li>
                            <li><a href="#">Italie</a></li>
                            <li><a href="#">Portugal</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Océanie</a>
                        <i class="fas fa-caret-right" id="dropdown7"></i>
                        <ul class="dropdownOceanie" id="dropdownOceanie">
                            <li><a href="#">Australie</a></li>
                            <li><a href="#">Nouvelle Calédonie</a></li>
                            <li><a href="#">Nouvelle Zélande</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="#">Astuces & bons plans</a></li>
            <li><a href="#">Communauté des voyageurs</a></li>
            <li><a href="#">Vidéos</a></li>
        </ul>
    </nav>
    <!-- navbar -->

</header>

<main>
    <div class="backgroundImage">

        {% block content %}
        {% endblock %}

    </div>
</main>

<footer>
    <div class="footerPresentation"><a href="#" id="footerTitle1">Présentation</a></div>
    <div class="footerDestinations"><a href="#" id="footerTitle2">Destinations</a>
        <div class="footerDestinations1">
            <div class="footerDestinationsLeft">
                <a href="#">Afrique</a>
                <a href="#">Amérique du nord</a>
                <a href="#">Amérique du sud</a>
            </div>
            <div class="footerDestinationsRight">
                <a href="#">Europe</a>
                <a href="#">Asie</a>
                <a href="#">Océanie</a>
            </div>
        </div>
    </div>
    <div class="footerAstuces"><a href="#" id="footerTitle3">Astuces & bons plans</a>
        <a href="#">Par pays</a>
        <a href="#">Par thèmes</a>
        <a href="#">Par continent</a>
    </div>
    <div class="footerCommunaute"><a href="#" id="footerTitle4">Communauté</a>
        <a href="#">Forum</a>
        <a href="pages/article_form.php">Connexion</a>
        <a href="#">Recherche membre</a>
    </div>
    <div class="footerVideos">
        <a href="#" id="footerTitle5">Vidéos</a>
    </div>
    <div>
        <a href="{{ path ('admin') }}">Admin</a>
    </div>
</footer>

<script type="text/javascript" src="{{ asset('assets/js/script.js')}}"></script>
</body>
</html>

templates/baseAdmin.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf8">
    <title>Tour du monde</title>
    <link rel="stylesheet" href="{{ asset('assets/css/styleBase.css') }}">
    {% block stylesheet %}{% endblock %}
    <script src="https://kit.fontawesome.com/21629f9ec4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
</head>
<body>
<header>
    <!-- haut du header -->
    <div class="topHeader">
        <img src="{{ asset('assets/img/logoTDM.png')}}" alt="logo" class="logoTop">
        <h1>Tour du monde</h1>
        <div class="rightHeader">
            <form action="{{ path('article_search') }}" method="get">
                <input type="text" class="barreRecherche" name="word">
                <input type="submit" class="button" value="Rechercher">
            </form>
        </div>
    </div>
    <!-- haut du header -->

    <!-- navbar -->
    <nav>
        <ul class="navbar" id="navbar">
            <li><a href="{{ path('index') }}">Accueil</a></li>
            <li><a href="{{ path('presentation') }}">Présentation</a></li>
            <li><a href="{{ path('contact') }}">Contact</a></li>
        </ul>
    </nav>
    <!-- navbar -->

</header>

<main>
    <div class="backgroundImage">

        {% block content %}
        {% endblock %}

    </div>
</main>

<footer>
    <ul class="navbar">
        <li><a href="{{ path('index') }}">Accueil</a></li>
        <li><a href="{{ path('presentation') }}">Présentation</a></li>
        <li><a href="{{ path('contact') }}">Contact</a></li>
        <li><a href="{{ path('admin') }}">Admin</a></li>
    </ul>
</footer>

<script type="text/javascript" src="{{ asset('assets/js/script.js')}}"></script>
</body>
</html>

templates/contact.html.twig
{% extends 'base.html.twig' %}
{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('assets/css/styleContact.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="contactTitle">Contact</h1>
        <p class="contactContenu">Pour nous contacter ou pour toutes questions merci de nous écrire à l'adresse
            suivante:</p>
        <p class="contactMail">mail@mail.com</p>
    </div>

{% endblock %}

templates/destinations.html.twig
{% extends 'base.html.twig' %}
{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('assets/css/articleList.css') }}">
{% endblock %}

{% block content %}

    <div class="indexContainer">
        {% for article in article %}
            <div class="articleContainer">
                <a href="{{ path('articleShow', {'id' : article.id}) }}">
                    <div class="imgContainer">
                        <img class="imgArticle" src="{{ asset('assets/img') }}/{{ article.picture }}" alt="image">
                    </div>
                    <h1 class="titleArticle">{{ article.titre }}</h1>
                    <div class="subtitleContainer">
                        <h2 class="subtitleArticle">Catégorie: {{ article.Categorie.libelle }}</h2>
                        <h2 class="subtitleArticle">Écrit par: {{ article.user.username }}</h2>
                        <h2 class="subtitleArticle">Pays: {{ article.pays.nomPays }}</h2>
                    </div>
                    <p>{{ article.contenu|striptags|slice(0, 755)|raw }} {{ "..." }} <a href="{{ path('articleShow', {'id' : article.id}) }}" class="linkArticle">Lire
                            plus</a></p>
                </a>
            </div>

        {% endfor %}
    </div>

{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
{% endblock %}

templates/presentation.html.twig
{% extends 'base.html.twig' %}
{% block stylesheet %}
<link rel="stylesheet" href="{{ asset('assets/css/presentation.css') }}">
{% endblock %}
{% block title %}Présentation{% endblock %}

{% block content %}

    <div class="presentationContainer">
        <h1 class="presentationTitle">Qui sommes-nous?</h1>

        <p class="presentationContenu">
            Nous sommes Cyril & Aline, Palois d’adoption, mais Périgourdin de coeur. Passionnés de voyages et de montagnes,
            nous avons rejoint le Béarn en 2015 pour être plus proche de nos jolies Pyrénées. Depuis 2016, mini-trotteur
            nous a rejoint, et nous voyageons désormais à 3.
        </p>


            <h2 class="presentationSubtitle">Cyril </h2>
            <p class="presentationContenu">
            Chef d’entreprise à Camperbasque .<br><br>

            Autodidacte et touche à tout, j’ai chopé le virus du voyage en 2007 quand je suis parti en Australie enchaîner 2
            PVT, après ma première immersion anglophone en Irlande.<br><br>

            Ayant eu déjà 2 vans entre l’Australie et la Nouvelle-Zélande, ce n’est que 2 ans après notre retour en France
            que nous avons décidé d’en acheter un et le faire aménager cette fois par un pro. Nous avons fait appel à Julien
            et son entreprise Campervans Montblanc pour réaliser notre aménagement tout bois dont nous sommes dingues!!^^
            Ce fut ensuite le début de l’aventure Camperbasque, atelier d’aménagement que j’ai ouvert en parallèle avec Julien
            depuis Septembre 2018. Depuis c’est l’aventure et la satisfaction permanente dans le boulot, et je ne changerai
            cela pour rien au monde!<br><br>

            Un bon jour de repos typique selon moi est un jour passé dans la nature!!<br><br>

            Concernant le blog, je m’occupe des photos et vidéos. J’aime bien donné quelques idées aussi à Aline, et lui
            corriger ses fautes 😉<br><br>

            Les voyages à mon actif : Irlande, Australie, Nouvelle-Zélande, Samoa, Espagne et les Baléares, Maroc, Indonésie,
            Italie, Angleterre, Suisse, Singapour, Hong-Kong et la Finlande.
        </p>

        <h2 class="presentationSubtitle">Aline</h2>
        <p class="presentationContenu">
            Dans la vie de tous les jours je suis Aide Médico-Psychologique, mais j’aime par-dessus tout les grands espaces,
            les voyages et la montagne été comme hiver! Avant de rencontrer Cyril je n’avais pas tellement voyagé, mais il a
            su me transmettre cette passion… Nous nous sommes envolés tous les deux pour un PVT en Nouvelle-Zélande, où nous
            avons passé 7 mois. Premier grand voyage pour moi, il m’a permis de m’ouvrir un peu plus! Maintenant j’ai envie
            de découvrir tellement d’endroits, que Cyril doit freiner mon impulsivité parfois !<br><br>

            Entre nous je m’occupe du blog en lui-même (et je suis loin d’être une pro!!), j’écris les articles, et je publie
            sur instagram!<br><br>

            Les voyages à mon actif : France, Espagne et Baléares, Nouvelle-Zélande, Hong-Kong, Indonésie, Samoa, Italie,
            Angleterre, Suisse, Singapour et la Finlande.
        </p>


        <h2 class="presentationSubtitle">Maé</h2>
        <p class="presentationContenu">
            Notre mini-trotteurs qui a 3 ans, aime déjà beaucoup la nature et s’y balader! Il a pris l’avion pour la première
            fois à 2ans et demi pour aller à Majorque. Il adore les road trip en van et y dormir, c’est un peu l’aventure!!
            Il aime aussi tremper ses pieds dans les rivières, y jeter des cailloux …
        </p>
    </div>

{% endblock %}